name: 'Setup Uffizzi CLI Binaries'
description: 'k8s cluster Preview Environments for every pull request. Supports APIs, frontends, backends, databases, and microservices.'
author: 'Gopal Nambiar'
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  release-tag:
    description: 'Tag for the CLI release'
    required: true
    default: 'latest'
  binary-name: 
    description: 'Name of the CLI binary'
    required: true
    default: 'uffizzi-linux'

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      wget https://github.com/UffizziCloud/uffizzi_cli/releases/download/v2.0.25/uffizzi-linux --quiet
      chmod +x ${{ inputs.binary-name }}

