name: 'Setup Uffizzi CLI Binaries'
description: 'k8s cluster Preview Environments for every pull request. Supports APIs, frontends, backends, databases, and microservices.'
author: 'Gopal Nambiar'
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  release-tag:
    description: 'Tag for the CLI release'
    required: true
    default: 'TEST-23'
  binary-name: 
    description: 'Name of the CLI binary'
    required: true
    default: 'uffizzi-TEST-23-linux-x86_64'

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      wget https://github.com/UffizziCloud/uffizzi_cli/releases/download/${{ inputs.release-tag }}/${{ inputs.binary-name }} --quiet
      chmod +x ${{ inputs.binary-name }}
  - name: Export the binary
    uses: actions/upload-artifact@v3
    with:
      name: my-artifact
      path: ${{ inputs.binary-name }}

