name: 'Setup Uffizzi CLI Binaries'
description: 'k8s cluster Preview Environments for every pull request. Supports APIs, frontends, backends, databases, and microservices.'
author: 'Gopal Nambiar'
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  release-tag:
    description: 'Tag for the CLI release'
    required: true
    default: 'v'
  binary-name: 
    description: 'Name of the CLI binary'
    required: true
    default: 'uffizzi-linux-x64-TEST-1'

runs:
  using: 'composite'
  steps:
  - shell: bash
    # Check if the input variable `action` is create
    run: |
      export UFFIZZI_SERVER=app.uffizzi.com
      export REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN}
      export REQUEST_TOKEN_URL=${ACTIONS_ID_TOKEN_REQUEST_URL}

      wget https://github.com/UffizziCloud/uffizzi_cli/releases/download/${{ inputs.release-tag }}/${{ inputs.binary-name }} --quiet
      chmod +x ${{ inputs.binary-name }}

      # echo ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}

      # ./${{ inputs.binary-name }} config set REQUEST_TOKEN ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}
      # ./${{ inputs.binary-name }} config set REQUEST_TOKEN_URL ${ACTIONS_ID_TOKEN_REQUEST_URL}

      echo "abc"
      echo $REQUEST_TOKEN_URL
      echo $REQUEST_TOKEN
      echo "def"

      # OIDC_TOKEN=$(curl -sLS ${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=uffizzi -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}")
      OIDC_TOKEN=$(curl -sLS "$REQUEST_TOKEN_URL&audience=uffizzi" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $REQUEST_TOKEN")
      echo $OIDC_TOKEN


      ./${{ inputs.binary-name }} login_by_identity_token --token ${OIDC_TOKEN} --access-token ${ACCESS_TOKEN} --server=app.uffizzi.com 
